language: android
jdk: oraclejdk8
dist: trusty

android:
  components:
    - build-tools-30.0.2
    - android-30
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-30
  licenses:
    - 'android-sdk-license-.+'


script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - ./gradlew clean
  - ./gradlew assembleDebug --stacktrace
  - ./gradlew test

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
